# Generated by Django 2.1.1 on 2018-11-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bargain_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bargain_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
