# Generated by Django 2.1.1 on 2018-11-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20181121_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bargain_amount_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='bargain_deadline_email',
            field=models.BooleanField(default=False),
        ),
    ]
